config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  
  get '/home', to: "pages#home"
  resources :recepies
  resources :chefs
  
  get'login' , to: "login#new"
  post'login' , to: "login#create"
  get'logout' , to: "login#destroy"
  
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recepies, class_name: "Recepie"
  has_many :likes 
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: {minimum: 3 , maximum: 100 }
  validates :email, presence: true, uniqueness: {case_sensitive: false},
                                            format: {with: VALID_EMAIL_REGEX }
                                            
  has_secure_password                                         
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recepie
end

app/models/purge_token.rb
class PurgeToken < ActiveRecord::Base
  require 'benchmark'
  #binding.pry
  #serialize :field, JSON
  p Benchmark.measure{ serialize :field, JSON}
end

app/models/recepie.rb
class Recepie < ActiveRecord::Base
  belongs_to :chef
  has_many :likes 
  validates :name,  presence: true, length: {minimum: 3 , maximum: 100 } 
  validates :summary,:description,  presence: true, length: {minimum: 4 , maximum: 400 }
  validates :chef_id, presence: true
  mount_uploader :picture , PictureUploader
  validate :picture_size
  
  private 
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "Should be less than 5MB")
    end
  end
  
end

app/models/sample_chefs.rb
class SampleChefs < ActiveRecord::Base

end

app/models/sample_recepie.rb
class SampleRecepie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

def index 
  
  @chef = Chef.all
  
end

def show
  
  @chef = Chef.find(params[:id])
  
end



end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  
  def new
    @chef = Chef.new
  end
  
  def create 
  end
  
  def destroy
  end
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    p "Hello"
  end
  
end 

app/controllers/purge_controller.rb
class PurgeController < ApplicationController
  require 'benchmark'
 @@chef = Chef.first
 
 def create(request_params)
    p Benchmark.measure{ @recepie = PurgeToken.new(request_params)}
    
    p Benchmark.measure {@recepie.save}
    
 end

end

purge = PurgeController.new

purge.create(@@che)

app/controllers/recepies_controller.rb
class RecepiesController < ApplicationController
  
   
  def index
    @recepies = Recepie.all
  end
  
  def show
    @recepie = Recepie.find(params[:id])
  end
  
  def new
    @recepie = Recepie.new
  end

  # This is just a comment
  
  def create
    @recepie = Recepie.new(request_params)
    @recepie.chef = Chef.find(1)
  
    if @recepie.save
      flash[:success] = "Recepie has been added"
      redirect_to recepies_path
    else 
    render :new
    end\
  end
  
  def edit
    @recepie =Recepie.find(params[:id])
  end
  
  def update
    @recepie =Recepie.find(params[:id])
    if @recepie.update(request_params)
      flash[:success] = "You have successfully edited your recepie"
      redirect_to recepy_path(@recepie)
    else
      render :edit
    end
  end
  
  
  private 
    
    def request_params
      params.require(:recepie).permit(:name,:summary,:description,:picture)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = {size:80})
  gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
  size = options[:size]
  
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  
  image_tag(gravatar_url , alt: chef.name, class: "gravatar")
  end
  
end

app/views/chefs/index.html.erb
<h1>List of all the chefs registered </h1>
<% @chef.each do |chef| %>
  <div class= "row">
    <div class = "col-md-2 show_recepie">
        <%= gravatar_for chef, size:100 %> 
        <h5><%= link_to "#{chef.name}", chef_path(chef.id) %></h5>
    </div>
    
    <div class = "col-md-10 well">
      <h2> Some information about the chef, must be added later </h2>
      
    </div>
  </div>
<% end %>
    
           

app/views/chefs/show.html.erb
<h1><%= @chef.name %></h1>
<div class = "centre ">
  <%= gravatar_for @chef, size:200 %>
  <h5> <%= @chef.name %> </h5>
</div>

<% @chef.recepies.each do |recepie| %>
  <li><h3> <%= link_to "#{recepie.name}" , recepy_path(recepie.id) %> </h3></li>
  <div class = 'row'>
    
    <div class = 'col-md-9 well'>
      <li><h4><%= recepie.summary %></h4></li>
      <Strong>Steps involved</Strong>
      <li><p> <%= recepie.description %></p></li>
    </div>
      
    <div class = "col-md-3 show_recepie pull-right">
      <%= image_tag(recepie.picture.url , size: "100x100" , class: "gravatar") if recepie.picture? %>
    </div>
  </div>
<% end %>
        

  

      
     

app/views/layouts/_footer.html.erb
<div class="footer">
  <p> &copy; MyApp </p>
</div>

app/views/layouts/_messages.html.erb
<div class = "row">
  <div class = "col-md-10">
    
    <% flash.each do |message_type , message| %>
      <div class = "alert alert-<%=message_type%>">
        <%= message %>
        <a class = "close" data-dismiss = "alert"> &#215; </a>
      </div>
    <% end %>
    
  </div>
  
</div>

app/views/layouts/_nav.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "MyStuff", root_path , class: "btn btn-lg btn-success", id:"logo" %>
    <div class="nav-item">
      <%= link_to "link1","",class: "btn btn-default btn-warning" %>
    </div>
    <div class="nav-item">
      <%= link_to "link1","",class: "btn btn-default btn-warning" %>
    </div>
    <div class="nav-item">
      <%= link_to "New Recepie",new_recepy_path,class: "btn btn-default btn-warning" %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/nav" %>
  <%= render "layouts/messages" %>
  <div class ="container">
    <%= yield %> 
    <%= render "layouts/footer" %>
  </div>

</body>
</html>

app/views/login/new.html.erb
<h1> Log in </h1>

<div class = "row" >
  
  <div class = "col-md-6 col-md-offset-3">
    
    <%= form_for @chef do |f|  %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      
      <%= f.label :password %>
      <%= f.text_field :password %>

      
      <%= f.submit("Submit" , class: "btn btn-success") %>
    
    <% end %>
    
  </div>
</div>

app/views/pages/home.html.erb
<div class="centre jumbotron">
  <h1> Welcome to the App </h1>
  
  <h2> 
    This is the home page of the application where you can signup
  </h2>
  
  <%= link_to "Sign Up", "", class: "btn btn-lg btn-success" %>
</div>

<div class="row">
  <div class= "col-lg-4">
    <h3 class="middrow"> Guest User</p>
    <h2 class= "left"> This makes you browse the recepies as a guest </p>
    <%= link_to "Recepies", recepies_path , class: "btn btn-warning btn-small" %>
  </div>
  
   <div class= "col-lg-4">
    <h3 class="middrow"> Some other options</p>
    <h2 class= "left"> This option is to execute this option and sign up later</p>
    <%= link_to "browse options", "", class: "btn btn-warning btn-small" %>
  </div>
  
   <div class= "col-lg-4">
    <h3 class="middrow"> Some other options</p>
    <h2 class= "left"> This option is to execute this option and sign up later</p>
    <%= link_to "browse options", "", class: "btn btn-warning btn-small" %>
  </div>
  
   
</div>

app/views/recepies/_form.html.erb
<div class = "row">
  <div class = "well col-md-8 col-md-offset-2">
    <%= form_for(@recepie, html: { multipart: true }) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: "10" %>
      
      <span class = "picture"><%= f.file_field :picture , accept: 'image/jpeg,image/png,image/gif' %></span>
      
      <%= f.submit(@recepie.new_record? ? "New Recepie" : "Edit Recepie" , class: "btn btn-success") %>
    <% end %>
      
  </div>
</div>

app/views/recepies/edit.html.erb
<h1> Edit Recepie</h1>

<%= render "shared/errors" , obj: @recepie %>

<%= render "form" %>

app/views/recepies/index.html.erb
<h1> All Recepies</h1>
  <hr>
    <% @recepies.each do |recepie| %>
      <div class= "row">
        <div class = "col-md-2">
          <section class= "chef_info center">
            <%= gravatar_for recepie.chef, size:100 %>  
            <h5><%= recepie.chef.name %></h5>
          </section>
        </div>
        <div class = "col-lg-6 well" >
          <h4> <%= link_to recepie.name, recepy_path(recepie) %> </h4>
          <p> <%= recepie.summary %> </p>
          <p class="quite"> <small> <%= time_ago_in_words(recepie.created_at) %> ago </small> </p>
        </div>
        <div class = 'col-md-4'>
          <%= image_tag(recepie.picture.url , size: '250x150' , class: "gravatar") if recepie.picture? %>
        </div>
      </div>
    
    <% end %>
  <hr>
</div>

app/views/recepies/new.html.erb
<h1> Create a New Recepie</h1>

<% if @recepie.errors.any? %>
  <div class = "row">
    <div class = "col-md-8 col-md-offset-2">
      <h3> Please correct the following errors </h3>
      <ul><% @recepie.errors.full_messages.each do |errors| %> 
        <li><%= errors %></li>
      <% end %>
      </ul>
        
    </div>
  </div>
  <% end %>
<div class = "row">
  <div class = "well col-md-8 col-md-offset-2">
    <%= form_for @recepie do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: "10" %>
      
      <%= f.submit "Create Recepie" , class: "btn btn-success" %>
    <% end %>
      
  </div>
</div>

app/views/recepies/show.html.erb
<h1><%= @recepie.name %></h1>

<div class= "row">
  
  <div class = "col-md-4 pull-right centre">
    <%= gravatar_for @recepie.chef, size:200 %>
    <h5> Brought to you by: <%= @recepie.chef.name %> </h5>
  </div>
  <h4><%= @recepie.summary %></h4>
 
  <div class = "show_recepie">
    <%= image_tag(@recepie.picture.url , size: "300x250" , class: "gravatar") if @recepie.picture? %>
  </div>
  
  
  <div class = "col-md-8 well">
     
    
    <Strong>Steps involved</Strong>
    <p> <%= @recepie.description %></p>
    <div class = 'pull-right'>
      <%= link_to '' do %>
        <i class = "glyphicon glyphicon-thumbs-up"></i>
      <% end %>&nbsp &nbsp&nbsp &nbsp
      <%= link_to '' do %>
        <i class = "glyphicon glyphicon-thumbs-down"></i>
      <% end %>
     </div>
  </div>
  
  <div class ="col-md-1.5 pull-right">
    <%= link_to "Edit Recepie", edit_recepy_path(@recepie.id), class: "btn btn-success" %>
  </div>                                                                                                                                                                                                                                                                                                                                   
</div>

<h5> <%= link_to "Return", recepies_path, class: "btn btn-warning btn-small " %> </h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class = "row">
    <div class = "col-md-8 col-md-offset-2">
      <h3> Please correct the following errors </h3>
      <ul><% obj.errors.full_messages.each do |errors| %> 
        <li><%= errors %></li>
      <% end %>
      </ul>
        
    </div>
  </div>
<% end %>